#!/usr/bin/env python3
"""export_project_plan — turn a generated project-plan.json into a
CSV/XLSX file the customer can import into their PM tool.

Supports four output formats:
  - clickup   ClickUp.com CSV import (the most-requested one)
  - asana     Asana CSV import
  - monday    Monday.com Excel import
  - generic   Tool-agnostic CSV — every field exposed, customer maps columns

Why this matters: every PM tool wants a slightly different CSV column
naming + structure. Doing this with "Claude generates the CSV at runtime"
is brittle — different Claude runs produce different headers + the
customer has to figure out which CSV upload error means what. A
deterministic script gives the customer a one-line command + a
predictable, well-tested output.

Usage:
  python3 export_project_plan.py \\
    --plan clients/{slug}/wqa/audits/{audit_id}/{slug}-project-plan.json \\
    --format clickup \\
    --output exports/project-plans/{slug}-clickup.csv

  # XLSX flavor (Monday + Excel-using teams)
  python3 export_project_plan.py \\
    --plan clients/{slug}/wqa/audits/{audit_id}/{slug}-project-plan.json \\
    --format monday \\
    --output exports/project-plans/{slug}-monday.xlsx

The plan JSON is generated by build_project_plan.py and has the shape:
  {
    "project": {...},
    "sprints": [...],
    "deliverables": [
      {id, sprint_number, name, description, deliverable_type, priority,
       assigned_to_email, start_date, due_date, scheduled_month, status,
       is_monthly_report, is_heavy_batch, is_strategy, is_placeholder,
       auto_tracked, source, ...}
    ]
  }
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from typing import Iterable


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

PRIORITY_MAP_CLICKUP = {"P1": "Urgent", "P2": "High", "P3": "Normal"}
PRIORITY_MAP_ASANA   = {"P1": "High",   "P2": "Medium", "P3": "Low"}
PRIORITY_MAP_MONDAY  = {"P1": "High",   "P2": "Medium", "P3": "Low"}


def load_plan(path: str) -> dict:
    if not os.path.exists(path):
        sys.exit(f"ERROR: plan file not found at {path}")
    return json.load(open(path))


def sprint_name(plan: dict, n: int) -> str:
    """Resolve sprint name from the plan's sprints array."""
    for s in plan.get("sprints", []):
        if s.get("sprint_number") == n:
            return s.get("name", f"Sprint {n}")
    return f"Sprint {n}"


def deliverable_tags(d: dict) -> list[str]:
    """Return a sorted, deduped list of tags to include in CSV exports."""
    tags = [
        d.get("deliverable_type", "").lower().replace(" ", "-"),
        d.get("priority", "").lower(),
    ]
    if d.get("is_monthly_report"): tags.append("monthly-report")
    if d.get("is_heavy_batch"):    tags.append("heavy-batch")
    if d.get("is_strategy"):       tags.append("strategy")
    if d.get("auto_tracked"):      tags.append("auto-tracked")
    if d.get("content_subtype"):   tags.append(f"content-{d['content_subtype']}")
    if d.get("link_subtype"):      tags.append(f"link-{d['link_subtype']}")
    return sorted({t for t in tags if t})


def short_owner(email: str | None) -> str:
    """Convert 'cesar@webris.org' -> 'cesar'. Empty if no email."""
    if not email:
        return ""
    return email.split("@")[0]


def status_for_tool(status: str, tool: str) -> str:
    """Map plan status → tool-native status.

    Plan statuses: pending, scheduled, working, completed, approved, delayed, rejected, ...
    """
    if status == "completed" or status == "approved":
        if tool == "clickup": return "Complete"
        if tool == "asana":   return "Complete"
        if tool == "monday":  return "Done"
        return "Done"
    if status == "rejected":
        # PM tools don't have a "rejected" concept — most customers want these archived/closed
        if tool == "monday": return "Stuck"
        return "Closed"
    if status == "delayed":
        if tool == "clickup": return "In Progress"
        if tool == "monday":  return "Stuck"
        return "In Progress"
    if status == "working":
        return "In Progress" if tool != "monday" else "Working on it"
    # Default: To Do
    if tool == "monday": return "Not Started"
    return "To Do"


def description_for(d: dict, plan: dict) -> str:
    """Build a rich description body for a deliverable. Includes context the
    PM tool wouldn't otherwise know (source category, URLs in batches, etc.)"""
    parts = [(d.get("description") or "").strip()]
    src = d.get("source") or {}
    if src.get("category"):
        parts.append(f"\n— Category: {src['category']}")
    if src.get("action_type"):
        parts.append(f"— Action: {src['action_type']}")
    if src.get("frequency"):
        parts.append(f"— Frequency: {src['frequency']}")
    if d.get("auto_tracked"):
        parts.append(f"\n⚙ Auto-tracked deliverable — completes when {d.get('auto_complete_artifact', 'the artifact')} is produced.")
    if d.get("is_placeholder"):
        parts.append("\n📝 Placeholder — strategist will expand during deep-dive.")
    # If URLs are present (typical for content/link batches), include them
    urls = src.get("urls") or src.get("target_pages") or []
    if urls:
        parts.append(f"\n— {len(urls)} URLs:")
        for u in urls[:30]:
            parts.append(f"  • {u}")
        if len(urls) > 30:
            parts.append(f"  • …and {len(urls) - 30} more")
    return "\n".join(p for p in parts if p)


# ---------------------------------------------------------------------------
# Per-tool exporters
# ---------------------------------------------------------------------------

def export_clickup(plan: dict, output: str) -> int:
    """ClickUp CSV import — needs: Task Name, Task Content, Assignee,
    Due Date, Start Date, Priority, Status, Tags, Time Estimate, Parent Task."""
    rows = []
    deliv = sorted(plan["deliverables"], key=lambda d: (d.get("sprint_number", 0), d.get("due_date") or ""))
    for d in deliv:
        if d.get("status") == "rejected":
            continue  # rejected items don't belong in the PM tool
        rows.append({
            "Task Name":    d.get("name", ""),
            "Task Content": description_for(d, plan),
            "Assignee":     d.get("assigned_to_email", ""),
            "Due Date":     d.get("due_date", ""),
            "Start Date":   d.get("start_date", ""),
            "Priority":     PRIORITY_MAP_CLICKUP.get(d.get("priority") or "", "Normal"),
            "Status":       status_for_tool(d.get("status", "pending"), "clickup"),
            "Tags":         ", ".join(deliverable_tags(d)),
            "Time Estimate": "",   # tool-specific; left blank, customer can backfill
            "Parent Task":  sprint_name(plan, d.get("sprint_number", 0)),
        })
    _write_csv(output, rows)
    return len(rows)


def export_asana(plan: dict, output: str) -> int:
    """Asana CSV import — needs: Name, Notes, Assignee, Due Date,
    Section/Column, Tags, Priority. Asana groups by Section/Column."""
    rows = []
    deliv = sorted(plan["deliverables"], key=lambda d: (d.get("sprint_number", 0), d.get("due_date") or ""))
    for d in deliv:
        if d.get("status") == "rejected":
            continue
        rows.append({
            "Name":            d.get("name", ""),
            "Notes":           description_for(d, plan),
            "Assignee":        d.get("assigned_to_email", ""),
            "Due Date":        d.get("due_date", ""),
            "Start Date":      d.get("start_date", ""),
            "Section/Column":  sprint_name(plan, d.get("sprint_number", 0)),
            "Tags":            ", ".join(deliverable_tags(d)),
            "Priority":        PRIORITY_MAP_ASANA.get(d.get("priority") or "", "Medium"),
            "Status":          status_for_tool(d.get("status", "pending"), "asana"),
        })
    _write_csv(output, rows)
    return len(rows)


def export_monday(plan: dict, output: str) -> int:
    """Monday.com Excel import. Each row = item; Group is the sprint."""
    rows = []
    deliv = sorted(plan["deliverables"], key=lambda d: (d.get("sprint_number", 0), d.get("due_date") or ""))
    for d in deliv:
        if d.get("status") == "rejected":
            continue
        rows.append({
            "Name":        d.get("name", ""),
            "Description": description_for(d, plan),
            "Group":       sprint_name(plan, d.get("sprint_number", 0)),
            "Person":      d.get("assigned_to_email", ""),
            "Status":      status_for_tool(d.get("status", "pending"), "monday"),
            "Date":        d.get("due_date", ""),
            "Start Date":  d.get("start_date", ""),
            "Priority":    PRIORITY_MAP_MONDAY.get(d.get("priority") or "", "Medium"),
            "Tags":        ", ".join(deliverable_tags(d)),
        })
    if output.endswith(".xlsx"):
        _write_xlsx(output, rows, plan)
    else:
        _write_csv(output, rows)
    return len(rows)


def export_generic(plan: dict, output: str) -> int:
    """Generic CSV — every field, no tool-specific massaging.
    Customer maps columns themselves on import."""
    rows = []
    for d in plan["deliverables"]:
        if d.get("status") == "rejected":
            continue
        rows.append({
            "id":               d.get("id", ""),
            "sprint":           sprint_name(plan, d.get("sprint_number", 0)),
            "sprint_number":    d.get("sprint_number", ""),
            "name":             d.get("name", ""),
            "description":      d.get("description", ""),
            "deliverable_type": d.get("deliverable_type", ""),
            "priority":         d.get("priority", ""),
            "assigned_to":      d.get("assigned_to_email", ""),
            "assignee_short":   short_owner(d.get("assigned_to_email")),
            "start_date":       d.get("start_date", ""),
            "due_date":         d.get("due_date", ""),
            "scheduled_month":  d.get("scheduled_month", ""),
            "status":           d.get("status", "pending"),
            "is_monthly_report": str(d.get("is_monthly_report", False)),
            "is_heavy_batch":   str(d.get("is_heavy_batch", False)),
            "is_strategy":      str(d.get("is_strategy", False)),
            "is_placeholder":   str(d.get("is_placeholder", False)),
            "auto_tracked":     str(d.get("auto_tracked", False)),
            "content_subtype":  d.get("content_subtype", ""),
            "link_subtype":     d.get("link_subtype", ""),
            "tags":             ", ".join(deliverable_tags(d)),
            "category":         (d.get("source") or {}).get("category", ""),
            "action_type":      (d.get("source") or {}).get("action_type", ""),
            "urls":             "; ".join((d.get("source") or {}).get("urls") or []),
        })
    _write_csv(output, rows)
    return len(rows)


# ---------------------------------------------------------------------------
# Writers
# ---------------------------------------------------------------------------

def _write_csv(path: str, rows: list[dict]) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    if not rows:
        with open(path, "w", newline="", encoding="utf-8") as f:
            f.write("")
        return
    fieldnames = list(rows[0].keys())
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
        w.writeheader()
        w.writerows(rows)


def _write_xlsx(path: str, rows: list[dict], plan: dict) -> None:
    """XLSX writer using openpyxl. Used for Monday.com import + as a
    nicer-than-CSV option for any tool that accepts Excel."""
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment
    except ImportError:
        sys.exit("ERROR: openpyxl is required for XLSX output. Install with: pip install openpyxl")
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    wb = Workbook()
    ws = wb.active
    ws.title = "Project Plan"
    if not rows:
        wb.save(path)
        return
    fieldnames = list(rows[0].keys())
    # Header
    header_fill = PatternFill("solid", fgColor="2563EB")
    header_font = Font(name="Arial", size=11, bold=True, color="FFFFFF")
    for col_i, field in enumerate(fieldnames, 1):
        c = ws.cell(row=1, column=col_i, value=field)
        c.font = header_font
        c.fill = header_fill
        c.alignment = Alignment(vertical="center")
    # Body
    body_font = Font(name="Arial", size=10)
    for row_i, row in enumerate(rows, 2):
        for col_i, field in enumerate(fieldnames, 1):
            c = ws.cell(row=row_i, column=col_i, value=row.get(field, ""))
            c.font = body_font
            c.alignment = Alignment(vertical="top", wrap_text=field in ("Description", "Notes", "Task Content"))
    # Column widths — heuristic by header name
    widths = {"Name": 50, "Task Name": 50, "Description": 60, "Notes": 60, "Task Content": 60,
              "Tags": 25, "Group": 22, "Section/Column": 22, "Parent Task": 22}
    for col_i, field in enumerate(fieldnames, 1):
        col_letter = ws.cell(row=1, column=col_i).column_letter
        ws.column_dimensions[col_letter].width = widths.get(field, 16)
    # Freeze header row
    ws.freeze_panes = "A2"
    wb.save(path)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

FORMATS = {
    "clickup": export_clickup,
    "asana":   export_asana,
    "monday":  export_monday,
    "generic": export_generic,
}


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--plan", required=True, help="Path to the {slug}-project-plan.json file")
    p.add_argument("--format", required=True, choices=list(FORMATS.keys()),
                   help="Target PM tool format")
    p.add_argument("--output", help="Output file path. Defaults to "
                                     "exports/project-plans/{slug}-{format}.{ext} relative to cwd.")
    p.add_argument("--workspace-root", default=".", help="Workspace root for default output path resolution.")
    args = p.parse_args()

    plan = load_plan(args.plan)
    slug = plan.get("client_slug") or "plan"

    # Resolve output path
    if args.output:
        out = args.output
    else:
        ext = "xlsx" if args.format == "monday" else "csv"
        out = os.path.join(args.workspace_root, "exports", "project-plans",
                           f"{slug}-{args.format}.{ext}")

    # Dispatch
    fn = FORMATS[args.format]
    n_rows = fn(plan, out)

    print(f"\n✓ Exported {n_rows} deliverables to {out}")
    print(f"  Format: {args.format}")
    print(f"  Source: {args.plan}")

    # Show what was filtered
    n_total = len(plan.get("deliverables", []))
    n_rejected = sum(1 for d in plan["deliverables"] if d.get("status") == "rejected")
    if n_rejected:
        print(f"  Note: {n_rejected} rejected deliverable(s) excluded from export.")

    print()
    print("Next step:")
    if args.format == "clickup":
        print("  ClickUp → Space → ⋯ → Import → CSV. Map columns when prompted.")
    elif args.format == "asana":
        print("  Asana → Project → ⋯ → Import → CSV (or use https://csv-importer.com if needed).")
    elif args.format == "monday":
        print("  Monday.com → Board → ⋯ → Import items → Excel.")
    else:
        print("  Use this generic CSV with any tool — you'll need to map columns yourself.")


if __name__ == "__main__":
    main()
